server:
  port: 4560
  servlet:
    context-path: / #请求路径，可以自定义
  tomcat:
    max-swallow-size: -1
  shutdown: graceful

spring:
  datasource:
    url: jdbc:sqlite:/home/db/data.db
    driver-class-name: org.sqlite.JDBC
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8


mybatis:
  type-aliases-package: life.bienao.springboot.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml

jwt:
  header: Authorization


